-- This table stores the completion status of each topic for each user.
CREATE TABLE public.material_status (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL,
    topic text NOT NULL,
    is_completed boolean NOT NULL DEFAULT false,
    CONSTRAINT material_status_pkey PRIMARY KEY (id),
    CONSTRAINT material_status_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT material_status_user_id_topic_key UNIQUE (user_id, topic) -- Ensures a user can't have duplicate topics
);

-- Enable Row Level Security
ALTER TABLE public.material_status ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
-- This policy allows users to perform any action (SELECT, INSERT, UPDATE, DELETE) on rows that belong to them.
CREATE POLICY "Enable all actions for users based on user_id"
ON public.material_status
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
